name: Email Action Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 25ds1000071@ds.study.iitm.ac.in
        run: echo "Hello, world!"
